### ISSUE TITLE
feat: Allow user to specify output dir?

### ISSUE THREAD

**Issue by Leon-Africa** [aurora-is-near/hardhat-storage-layout#6]
````
  if (storageLayoutUserPath === undefined) {
      newStorageLayoutPath = path.join(config.paths.root, "./storageLayout");
    } else {
      if (path.isAbsolute(storageLayoutUserPath)) {
        newStorageLayoutPath = storageLayoutUserPath;
      } else {
        newStorageLayoutPath = path.normalize(
          path.join(config.paths.root, storageLayoutUserPath)
        );
      }
    }
````

[newStorageLayoutPath ](https://github.com/aurora-is-near/hardhat-storage-layout/blob/main/src/index.ts#:~:text=let%20newStorageLayoutPath%3A%20string%3B-,if%20(storageLayoutUserPath%20%3D%3D%3D%20undefined)%20%7B,%7D,-config.paths.newStorageLayoutPath)

````
if (!outputDirectory.startsWith(this.env.config.paths.root)) {
      throw new HardhatPluginError(
        "output directory should be inside the project directory"
      );
````

[storageLayout](https://github.com/aurora-is-near/hardhat-storage-layout/blob/main/src/storageLayout.ts#:~:text=if%20(!outputDirectory.startsWith,)%3B)

Seems to limit where the file will be outputted to - how about instead having the user specify any desired output dir?

**Comment by 0x3bfc** [comment]
fixed in #19
