### ISSUE TITLE
feat: Plugin could add "storageLayout" output automatically

### ISSUE THREAD

**Issue by frangio** [aurora-is-near/hardhat-storage-layout#9]
I don't think it's necessary to have users manually add the "storageLayout" compiler output. The plugin could use `extendConfig` to automatically add it in the config if not already present. [Here](https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/f3ef2483c61205f13cca14c4e457a3bcea78b43b/src/index.ts#L11) is an example use of `extendConfig`.

**Comment by frangio** [comment]
Is there any interest in a PR for this? It's very simple to add.

**Comment by 0x3bfc** [comment]
fixed in #19

**Comment by frangio** [comment]
Thanks. It seems there was a console.log left in the code:

https://github.com/aurora-is-near/hardhat-storage-layout/blob/b405e22cdf0ba26395b462da96cce5d764499d58/src/index.ts#L21

Also note that according to Hardhat recommendations the task to override is `TASK_COMPILE_SOLIDITY_GET_COMPILATION_JOB_FOR_FILE`.

https://github.com/NomicFoundation/hardhat/blob/5779b9f48ea303093b794fb46c37e7035567b44a/packages/hardhat-core/src/builtin-tasks/compile.ts#L205-L207
